version: "3.9"
services:
  web:
    build: .
    image: elitedivision/open-2.0
    ports:
      - "127.0.0.1:8443:443"
    volumes:
      - ./app:/var/www/app
    depends_on:
      - database
    networks:
      open2net:

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - dbdata:/var/lib/mysql
      - applog:/var/log
    expose:
      - "3306"
    networks:
      open2net:

  elasticsearch:
    image: elasticsearch:8.10.2
    restart: always
    volumes:
      - applog:/var/log
    expose:
      - "9200"
      - "9300"
    networks:
      open2net:

  antivirus:
    image: clamav/clamav:1.2
    restart: always
    volumes:
      - ./app:/var/www/app
      - applog:/var/log
    expose:
      - "3310"
    networks:
      open2net:
volumes:
  applog: {}
  dbdata: {}
networks:
  open2net: