name: Docker Image CI

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
  version: 'latest'
  dockerfile: 'Dockerfile'
  dockerdir: '.'

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['base', 'with-shibboleth']
    steps:
    - uses: actions/checkout@v3
    - name: Pre-Deploy
      if: ${{ matrix.version != 'base' }}
      env:
        version: ${{ matrix.version }}
        dockerdir: variants/${{ matrix.version }}
      run: echo "Switch to ${{ matrix.version }}"
    - name: Login to Hub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build ${{ env.dockerdir }} --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ env.version }}
    - name: Push Image
      run: docker push $DOCKER_USER/$REPO_NAME:${{ env.version }}
