name: Docker Image CI

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        php: ['7.0','7.4','8.2']
        variant: ['base', 'with-shibboleth', 'dev']
        include:
          - variant: 'base'
            tag: '${{ matrix.php }}'
          - variant: 'with-shibboleth'
            dockerdir: 'variants/with-shibboleth/'
            tag: '${{ matrix.php }}-${{ matrix.variant }}'
          - variant: 'dev'
            dockerdir: 'variants/dev/'
            tag: '${{ matrix.php }}-${{ matrix.variant }}'
    env:
      dockerfile: 'Dockerfile'
    steps:
    - uses: actions/checkout@v3
    - name: Login to Hub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build ${{ matrix.variant }} with PHP ${{ matrix.php }} Image
      run: >
        docker build ./${{ matrix.dockerdir }} 
        --build-arg "PHP_VERSION=${{ matrix.php }}" 
        --file ${{ matrix.dockerdir }}${{ env.dockerfile }} 
        --tag $DOCKER_USER/$REPO_NAME:${{ matrix.tag }}
    - name: Push ${{ matrix.variant }} with PHP ${{ matrix.php }} Image
      run: docker push $DOCKER_USER/$REPO_NAME:${{ matrix.tag }}
