name: Docker Image CI

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        variant: ['base','with-shibboleth']
    env:
      version: 'latest'
      dockerfile: 'Dockerfile'
      dockerdir: '.'
    steps:
    - uses: actions/checkout@v3
    - name: Login to Hub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Base Image
      if: ${{ matrix.variant == 'base' }}
      run: docker build ${{ env.dockerdir }} --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ env.version }}
    - name: Push Base Image
      if: ${{ matrix.variant == 'base' }}
      run: docker push $DOCKER_USER/$REPO_NAME:${{ env.version }}

    - name: Build Alternative Image
      if: ${{ matrix.variant != 'base' }}
      run: docker build variants/${{ matrix.variant }} --file variants/${{ matrix.variant }}/Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ matrix.variant }}
    - name: Push Alternative Image
      if: ${{ matrix.variant != 'base' }}
      run: docker push $DOCKER_USER/$REPO_NAME:${{ matrix.variant }}
