name: Docker Image CI

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        php: ['7.0','7.4','8.2','8.3','8.4']
        variant: ['base', 'with-shibboleth', 'dev']
        include:
          - variant: 'with-shibboleth'
            dockerdir: 'variants/with-shibboleth/'
          - variant: 'dev'
            dockerdir: 'variants/dev/'
    env:
      dockerfile: 'Dockerfile'
    steps:
    - uses: actions/checkout@v4

    - name: Set Docker Tag
      run: echo $([ "${{ matrix.variant }}" == "base" ] &&  echo "DOCKER_TAG=${{matrix.php }}" || echo "DOCKER_TAG=${{ matrix.php }}-${{ matrix.variant }}") >> $GITHUB_ENV

    - name: Login to Hub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build ${{ matrix.variant }} with PHP ${{ matrix.php }} Image
      run: >
        docker build ./${{ matrix.dockerdir }} 
        --build-arg "PHP_VERSION=${{ matrix.php }}" 
        --file ${{ matrix.dockerdir }}${{ env.dockerfile }} 
        --tag $DOCKER_USER/$REPO_NAME:${{ env.DOCKER_TAG }}

    - name: Push ${{ matrix.variant }} with PHP ${{ matrix.php }} Image
      run: docker push $DOCKER_USER/$REPO_NAME:${{ env.DOCKER_TAG }}

    - name: Tag ${{ matrix.variant }} with PHP ${{ matrix.php }} as Latest
      run: docker tag $DOCKER_USER/$REPO_NAME:${{ env.DOCKER_TAG }} $DOCKER_USER/$REPO_NAME:latest

    - name: Push Latest
      run: docker push $DOCKER_USER/$REPO_NAME:latest
